### ISSUE TITLE
Wagon Specs lokal ausführen

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/development#39]
Hallo zusammen

Ich würde gerne die Specs im PBS Wagon zum laufen bringen (und dann anpassen). Aber ich scheitere schon beim Ausführen der Anleitung. Hat jemand einen Tipp?

```
michael/workspace/hitobito$ export WAGON=pbs
michael/workspace/hitobito$ bin/test_env_wagon bundle exec rspec
Creating hitobito_rails_run ... done
⚙ Activating Wagonfile.development
Installing gems if necessary
⚙️  Testing DB connection
✅ DB server is ready
⚙️  Performing migrations
/opt/bundle/ruby/2.7.0/gems/pry-byebug-3.7.0/lib/pry-byebug/control_d_handler.rb:5: warning: control_d_handler's arity of 2 parameters was deprecated (eval_string, pry_instance). Now it gets passed just 1 parameter (pry_instance)
/usr/src/app/hitobito/config/initializers/person_language.rb:2: warning: already initialized constant Person::PUBLIC_ATTRS
/usr/src/app/hitobito/app/models/person.rb:67: warning: previous definition of PUBLIC_ATTRS was here
The database schema will not be dumped when there are loaded wagon migrations.
To dump the application schema, please 'rake wagon:remove WAGON=ALL' wagons beforehand or reset the database.
✅ Migrations done
↪️  Skipping seeding because already done on Tue Jan  4 15:48:03 UTC 2022
⚙️  Executing: bundle exec bash bundle exec rspec
/usr/local/bundle/bin/bundle: line 9: require: command not found
/usr/local/bundle/bin/bundle: line 11: version: command not found
/usr/local/bundle/bin/bundle: line 13: str: command not found
/usr/local/bundle/bin/bundle: bundle: line 15: syntax error near unexpected token `('
/usr/local/bundle/bin/bundle: bundle: line 15: `  str = str.b[/\A_(.*)_\z/, 1]'
michael/workspace/hitobito$ 
```

**Comment by carlobeltrame** [comment]
Ich führe es jeweils so aus:
```bash
$ WAGON=pbs bin/test_env_wagon
$ rspec spec/controllers/people_controller_spec.rb 
[DEPRECATED] Your Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config set disable_multisource true`.
ruby/2.7.5 isn't supported by this pry-doc version
 - CustomContent {:key=>"send_login", :placeholders_required=>"login-url", :placeholders_optional=>"recipient-name-with-salutation, recipient-name, sender-name"}
 - CustomContent {:key=>"event_application_confirmation", :placeholders_required=>"event-details, application-url", :placeholders_optional=>"recipient-name-with-salutation, recipient-name"}
 - CustomContent {:key=>"event_application_approval", :placeholders_required=>"participant-name, event-details, application-url", :placeholders_optional=>"recipient-names-with-salutation, recipient-names"}
 - CustomContent {:key=>"event_cancel_application", :placeholders_required=>"event-details", :placeholders_optional=>"recipient-name-with-salutation, recipient-name"}
 - CustomContent {:key=>"event_register_login", :placeholders_required=>"event-url", :placeholders_optional=>"recipient-name-with-salutation, recipient-name, event-name"}
 - CustomContent {:key=>"person_add_request_person", :placeholders_required=>"request-body, answer-request-url", :placeholders_optional=>"recipient-name-with-salutation, recipient-name, requester-name, requester-roles"}
 - CustomContent {:key=>"person_add_request_responsibles", :placeholders_required=>"person-name, request-body, answer-request-url", :placeholders_optional=>"recipient-names-with-salutation, recipient-names, requester-name, requester-roles"}
 - CustomContent {:key=>"person_add_request_approved", :placeholders_required=>"person-name, request-body", :placeholders_optional=>"recipient-name-with-salutation, recipient-name, approver-name, approver-roles"}
 - CustomContent {:key=>"person_add_request_rejected", :placeholders_required=>"person-name, request-body", :placeholders_optional=>"recipient-name-with-salutation, recipient-name, rejecter-name, rejecter-roles"}
Run options: exclude {:type=>"feature", :sphinx=>true, :performance=>true, :format=>:json}

Randomized with seed 27551
.

Finished in 0.85909 seconds (files took 7.48 seconds to load)
1 example, 0 failures

Randomized with seed 27551
```
Also ohne bundle exec, und stattdessen erst in der geöffneten Konsole im Container drin, statt direkt das Argument zu übergeben.
Wäre vermutlich aber auch gut wenn wir deinen Ansatz unterstützen würden.

Ich hatte gerade noch Probleme dass die Test-Migrationen nicht korrekt angewendet wurden. Im Wagon Test-Env hilft dann `../hitobito/bin/rails db:migrate RAILS_ENV=test` statt `bin/rails db:migrate RAILS_ENV=test` wie die Fehlermeldung meint.

**Comment by Michael-Schaer** [comment]
Merci Carlo, das hat schon mal geholfen. Musste zuerst die DB löschen und alles neu builden. Dann konnte ich aber die Test-Seeds wie von dir beschrieben durchlaufen lassen. Jetzt habe ich aber einen neuen Fehler. Komischerweise hat es zuerst einmal geklappt (der Test lief durch), aber das zweite mal nicht mehr...

Hast du da auch noch einen Tipp?

```
🚃 test 🕎 master 📁 /usr/src/app/hitobito_pbs $ rspec spec/controllers/people_controller_spec.rb 
[DEPRECATED] Your Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config set disable_multisource true`.
/opt/bundle/ruby/2.7.0/gems/pry-byebug-3.7.0/lib/pry-byebug/control_d_handler.rb:5: warning: control_d_handler's arity of 2 parameters was deprecated (eval_string, pry_instance). Now it gets passed just 1 parameter (pry_instance)
 - CustomContent {:key=>"send_login", :placeholders_required=>"login-url", :placeholders_optional=>"recipient-name-with-salutation, recipient-name, sender-name"}

An error occurred while loading ./spec/controllers/people_controller_spec.rb.
Failure/Error:
  CustomContent.seed(:key,
    { key: Person::LoginMailer::CONTENT_LOGIN,
      placeholders_required: 'login-url',
      placeholders_optional: 'recipient-name-with-salutation, recipient-name, sender-name'},
  
    { key: Event::ParticipationMailer::CONTENT_CONFIRMATION,
      placeholders_required: 'event-details, application-url',
      placeholders_optional: 'recipient-name-with-salutation, recipient-name'},
  
    { key: Event::ParticipationMailer::CONTENT_APPROVAL,

ActiveRecord::NotNullViolation:
  Mysql2::Error: Field 'label' doesn't have a default value
# /opt/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
# /opt/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
# /opt/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
# /opt/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:206:in `block (2 levels) in execute'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:205:in `block in execute'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:204:in `execute'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/mysql/database_statements.rb:50:in `execute'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:215:in `execute_and_free'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/mysql/database_statements.rb:55:in `exec_query'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `exec_insert'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:171:in `insert'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:375:in `_insert_record'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:929:in `_create_record'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/counter_cache.rb:166:in `_create_record'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/locking/optimistic.rb:79:in `_create_record'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/attribute_methods/dirty.rb:201:in `_create_record'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:461:in `block in _create_record'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:106:in `run_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:824:in `_run_create_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:461:in `_create_record'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/timestamp.rb:108:in `_create_record'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:900:in `create_or_update'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:457:in `block in create_or_update'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:106:in `run_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:457:in `create_or_update'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/timestamp.rb:126:in `create_or_update'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:474:in `save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/validations.rb:47:in `save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:298:in `block in save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:318:in `transaction'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:298:in `save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/suppressor.rb:44:in `save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/autosave_association.rb:506:in `save_belongs_to_association'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/autosave_association.rb:225:in `block in add_autosave_association_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/autosave_association.rb:181:in `instance_eval'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/autosave_association.rb:181:in `block in define_non_cyclic_method'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:603:in `catch'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:603:in `block in default_terminator'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:199:in `block in halting'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:512:in `block in invoke_before'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:512:in `each'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:512:in `invoke_before'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:115:in `block in run_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:457:in `create_or_update'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/timestamp.rb:126:in `create_or_update'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:474:in `save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/validations.rb:47:in `save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:298:in `block in save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:318:in `transaction'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:298:in `save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/suppressor.rb:44:in `save'
# /usr/src/app/hitobito/app/models/concerns/globalized.rb:32:in `block (2 levels) in translates_rich_text'
# /usr/src/app/hitobito/app/models/concerns/globalized.rb:31:in `each'
# /usr/src/app/hitobito/app/models/concerns/globalized.rb:31:in `block in translates_rich_text'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:427:in `instance_exec'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:516:in `block in invoke_after'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:516:in `each'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:516:in `invoke_after'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:107:in `run_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:824:in `_run_update_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:465:in `_update_record'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/timestamp.rb:121:in `_update_record'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:900:in `create_or_update'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:457:in `block in create_or_update'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/autosave_association.rb:385:in `around_save_collection_association'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/callbacks.rb:457:in `create_or_update'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/timestamp.rb:126:in `create_or_update'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/persistence.rb:474:in `save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/validations.rb:47:in `save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:298:in `block in save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:318:in `transaction'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:298:in `save'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/suppressor.rb:44:in `save'
# /opt/bundle/ruby/2.7.0/gems/globalize-6.0.1/lib/globalize/active_record/instance_methods.rb:166:in `block (2 levels) in save'
# /opt/bundle/ruby/2.7.0/gems/globalize-6.0.1/lib/globalize/active_record/instance_methods.rb:271:in `without_fallbacks'
# /opt/bundle/ruby/2.7.0/gems/globalize-6.0.1/lib/globalize/active_record/instance_methods.rb:165:in `block in save'
# /opt/bundle/ruby/2.7.0/gems/globalize-6.0.1/lib/globalize.rb:36:in `with_locale'
# /opt/bundle/ruby/2.7.0/gems/globalize-6.0.1/lib/globalize/active_record/instance_methods.rb:164:in `save'
# /opt/bundle/ruby/2.7.0/gems/seed-fu-2.3.9/lib/seed-fu/seeder.rb:74:in `seed_record'
# /opt/bundle/ruby/2.7.0/gems/seed-fu-2.3.9/lib/seed-fu/seeder.rb:36:in `block (2 levels) in seed'
# /opt/bundle/ruby/2.7.0/gems/seed-fu-2.3.9/lib/seed-fu/seeder.rb:36:in `map'
# /opt/bundle/ruby/2.7.0/gems/seed-fu-2.3.9/lib/seed-fu/seeder.rb:36:in `block in seed'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
# /opt/bundle/ruby/2.7.0/gems/activerecord-6.1.4.1/lib/active_record/transactions.rb:209:in `transaction'
# /opt/bundle/ruby/2.7.0/gems/seed-fu-2.3.9/lib/seed-fu/seeder.rb:35:in `seed'
# /opt/bundle/ruby/2.7.0/gems/seed-fu-ndo-0.0.3/lib/seed-fu-ndo/seeder.rb:14:in `seed_with_undo'
# /opt/bundle/ruby/2.7.0/gems/seed-fu-2.3.9/lib/seed-fu/active_record_extension.rb:32:in `seed'
# ./spec/support/custom_content_placeholders.rb:9:in `<main>'
# /opt/bundle/ruby/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
# /opt/bundle/ruby/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
# /opt/bundle/ruby/2.7.0/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
# ./spec/spec_helper.rb:15:in `block in <top (required)>'
# ./spec/spec_helper.rb:15:in `each'
# ./spec/spec_helper.rb:15:in `<top (required)>'
# ./spec/controllers/people_controller_spec.rb:8:in `require'
# ./spec/controllers/people_controller_spec.rb:8:in `<top (required)>'
# /opt/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
# /opt/bundle/ruby/2.7.0/bin/rspec:23:in `load'
# /opt/bundle/ruby/2.7.0/bin/rspec:23:in `<top (required)>'
# /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
# /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
# /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
# /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
# /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
# /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
# /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
# /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
# /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
# /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
# /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
# /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
# /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
# /usr/local/bundle/bin/bundle:23:in `load'
# /usr/local/bundle/bin/bundle:23:in `<main>'
# ------------------
# --- Caused by: ---
# Mysql2::Error:
#   Field 'label' doesn't have a default value
#   /opt/bundle/ruby/2.7.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
Run options: exclude {:type=>"feature", :sphinx=>true, :performance=>true, :format=>:json}

All examples were filtered out


Finished in 0.00004 seconds (files took 3.39 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

🚃 test 🕎 master 📁 /usr/src/app/hitobito_pbs $ 


```
